# Generated by Django 6.0.6 on 2026-06-28 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exposurerecord',
            index=models.Index(fields=['user', 'done_at'], name='records_exp_user_id_c8c79a_idx'),
        ),
    ]
