# Generated by Django 6.0.6 on 2026-06-28 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_exposurerecord_records_exp_user_id_c8c79a_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='uservalue',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_value_name'),
        ),
    ]
